services:
  # 後端服務
  - type: web
    name: travel-planner-api
    env: node
    region: singapore
    plan: free
    buildCommand: |
      cd server
      npm install
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: "5001"
      - key: MONGO_URI
        value: mongodb+srv://marmotkk2013:Kingmax00@marmotkit.dlnje.mongodb.net/travel_planner
      - key: JWT_SECRET
        value: your_very_secure_jwt_secret
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Content-Type
        value: application/json; charset=utf-8
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://travel-planner.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, PATCH, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Request-ID
      - path: /*
        name: Access-Control-Expose-Headers
        value: Content-Type, X-Request-ID
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate, proxy-revalidate
      - path: /*
        name: CDN-Cache-Control
        value: no-store, no-cache, must-revalidate, proxy-revalidate
      - path: /*
        name: Cloudflare-CDN-Cache-Control
        value: no-store, no-cache, must-revalidate, proxy-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: "0"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: same-origin
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains; preload
    healthCheckPath: /health
    autoDeploy: true
    domains:
      - api.travel-planner.onrender.com

  # 前端服務
  - type: static
    name: travel-planner-web
    env: static
    region: singapore
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: client/dist
    autoDeploy: true
    domains:
      - travel-planner.onrender.com
    envVars:
      - key: VITE_API_URL
        value: https://api.travel-planner.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html