services:
  # 後端服務
  - type: web
    name: travel-planner-api
    env: node
    rootDir: server
    runtime: node@16.x
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Node version: $(node --version)"
      echo "Installing dependencies..."
      npm install
      echo "Node_modules contents:"
      ls -la node_modules
      echo "Checking jsonwebtoken:"
      ls -la node_modules/jsonwebtoken || echo "jsonwebtoken not found"
    startCommand: |
      echo "Starting from directory: $(pwd)"
      echo "Node version: $(node --version)"
      node index.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://marmotkk2013:Kingmax00@marmotkit.dlnje.mongodb.net/travel_planner
      - key: JWT_SECRET
        value: your_very_secure_jwt_secret
      - key: NODE_ENV
        value: production

  # 前端服務
  - type: static
    name: travel-planner-web
    env: static
    rootDir: client
    runtime: node@16.x
    buildCommand: |
      echo "Node version: $(node --version)"
      echo "Installing dependencies..."
      npm install
      echo "Building..."
      npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://travel-planner-api.onrender.com/api 