services:
  - type: web
    name: travel-planner-api
    env: node
    buildCommand: |
      cd server
      npm install
      echo 'module.exports = {
        port: process.env.PORT || 5001,
        mongoUri: process.env.MONGO_URI || "mongodb://localhost:27017/travel_planner",
        jwtSecret: process.env.JWT_SECRET || "your_jwt_secret_here",
        jwtExpiresIn: "24h",
        nodeEnv: process.env.NODE_ENV || "development"
      };' > config/config.js
    startCommand: |
      cd server
      node index.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://marmotkk2013:Kingmax00@marmotkit.dlnje.mongodb.net/travel_planner
      - key: JWT_SECRET
        value: your_very_secure_jwt_secret
      - key: NODE_ENV
        value: production

  - type: static
    name: travel-planner-web
    env: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://travel-planner-api.onrender.com/api 