services:
  # 後端服務
  - type: web
    name: travel-planner-api
    env: node
    rootDir: server
    buildCommand: |
      pwd
      ls -la
      npm install --production
      ls -la node_modules/jsonwebtoken
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://marmotkk2013:Kingmax00@marmotkit.dlnje.mongodb.net/travel_planner
      - key: JWT_SECRET
        value: your_very_secure_jwt_secret
      - key: NODE_ENV
        value: production

  # 前端服務
  - type: static
    name: travel-planner-web
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://travel-planner-api.onrender.com/api 