services:
  # 後端服務
  - type: web
    name: travel-planner-api
    env: node
    buildCommand: |
      echo "=== Build Info ==="
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      
      echo "=== Installing Dependencies ==="
      cd server
      rm -rf node_modules package-lock.json
      npm install
      
      echo "=== Verifying Installation ==="
      echo "node_modules contents:"
      ls -la node_modules
      echo "Checking key dependencies:"
      ls -la node_modules/jsonwebtoken
      ls -la node_modules/express
      ls -la node_modules/mongoose
      
      echo "=== Setting up config ==="
      echo "module.exports = {
        jwtSecret: process.env.JWT_SECRET,
        mongoUri: process.env.MONGO_URI,
        port: process.env.PORT || 5001
      };" > config/config.js
    startCommand: cd server && node index.js
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://marmotkk2013:Kingmax00@marmotkit.dlnje.mongodb.net/travel_planner
      - key: JWT_SECRET
        value: your_very_secure_jwt_secret
      - key: NODE_ENV
        value: production

  # 前端服務
  - type: static
    name: travel-planner-web
    env: static
    rootDir: client
    buildCommand: |
      echo "=== Build Info ==="
      echo "Current directory: $(pwd)"
      echo "Node version: $(node --version)"
      
      echo "=== Installing Dependencies ==="
      rm -rf node_modules package-lock.json
      npm install
      
      echo "=== Building ==="
      npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://travel-planner-api.onrender.com/api 